"""Add unique constraint for patient_id and title in CarePlan

Revision ID: 6d0469635517
Revises: 32a6e2e2b64e
Create Date: 2025-06-18 16:34:30.609739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0469635517'
down_revision = '32a6e2e2b64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_plan', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_patient_title', ['patient_id', 'title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('care_plan', schema=None) as batch_op:
        batch_op.drop_constraint('uq_patient_title', type_='unique')

    # ### end Alembic commands ###
