"""Add goal_id to activity table

Revision ID: add_goal_id
Revises: fc80d4e0b3bf
Create Date: 2024-03-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_goal_id'
down_revision = 'fc80d4e0b3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_activity_goal_id', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activity_goal_id', type_='foreignkey')
    # ### end Alembic commands ### 