"""Add doctor fields to Activity table

Revision ID: add_doctor_fields
Revises: ea1504f72d97
Create Date: 2025-04-25 14:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_doctor_fields'
down_revision = 'ea1504f72d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('doctor_name', sa.String(length=100), nullable=True))
    op.add_column('activity', sa.Column('enable_reminder', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'enable_reminder')
    op.drop_column('activity', 'doctor_name')
    # ### end Alembic commands ### 